name: test
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - sympy>=1.0.0,<2.0.0
  - pandas>=0.21.0,<3.0.0
  - numpy>=1.13.0,<2.0.0
  - scikit-learn>=1.0.0,<2.0.0
  - pyjuliacall>=0.9.15,<0.10.0
  - click>=7.0.0,<9.0.0
  - typing_extensions>=4.0.0,<5.0.0
