name: Deploy PyPI
on:
  workflow_run:
    workflows: ["Linux", "macOS", "Windows"]
    types:
      - completed

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
      - name: "Install building tools"
        run: pip install wheel
      - name: "Build package"
        run: python setup.py sdist bdist_wheel
      - name: "Publish distribution ðŸ“¦ to Test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      - name: "Publish distribution ðŸ“¦ to PyPI"
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
